name: marketplace_release

on:
    push:
        tags:
            - v*.*.*

permissions:
    contents: read

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
              with:
                  egress-policy: audit
                  #ToDo: Change to block after couple of workflow runs

            - name: Checkout Repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Install Node 22
              uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
              with:
                  node-version: 22

            - name: Install Dependencies
              run: npm ci

            - name: Package Extension
              id: packageExtension
              uses: HaaLeo/publish-vscode-extension@ca5561daa085dee804bf9f37fe0165785a9b14db # v2.0.0
              with:
                  pat: ${{ secrets.AZURE_RELEASE_TOKEN }}
                  registryUrl: https://marketplace.visualstudio.com/
                  preRelease: true

            - name: Create Release
              uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ${{ steps.packageExtension.outputs.vsixPath }}

            - name: Upload Extension Package as Artifact
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
              with:
                  name: VSIX Extension File
                  path: ${{ steps.packageExtension.outputs.vsixPath }}
                  retention-days: 5
